package io.github.mojira.arisa.domain

import java.io.File
import java.time.Instant

data class Issue(
    val key: String,
    val summary: String?,
    val status: String,
    val description: String?,
    val environment: String?,
    val securityLevel: String?,
    val reporter: User?,
    val resolution: String?,
    val created: Instant,
    val updated: Instant,
    val resolved: Instant?,
    val chk: String?,
    val confirmationStatus: String?,
    val linked: Double?,
    val priority: String?,
    val triagedTime: String?,
    val project: Project,
    val platform: String?,
    val dungeonsPlatform: String?,
    val affectedVersions: List<Version>,
    val fixVersions: List<Version>,
    val attachments: List<Attachment>,
    val comments: List<Comment>,
    val links: List<Link>,
    val changeLog: List<ChangeLogItem>,
    val reopen: () -> Unit,
    val resolveAsAwaitingResponse: () -> Unit,
    val resolveAsInvalid: () -> Unit,
    val resolveAsDuplicate: () -> Unit,
    val resolveAsIncomplete: () -> Unit,
    val updateDescription: (description: String) -> Unit,
    val updateCHK: () -> Unit,
    val updateConfirmationStatus: (String) -> Unit,
    val updatePlatform: (String) -> Unit,
    val updateDungeonsPlatform: (String) -> Unit,
    val updateLinked: (Double) -> Unit,
    val setPrivate: () -> Unit,
    val addAffectedVersion: (id: String) -> Unit,
    val createLink: (type: String, key: String, outwards: Boolean) -> Unit,
    val addComment: (options: CommentOptions) -> Unit,
    val addRestrictedComment: (options: CommentOptions) -> Unit,
    val addNotEnglishComment: (language: String) -> Unit,
    val addRawComment: (body: String) -> Unit,
    val addRawRestrictedComment: (body: String, restriction: String) -> Unit,
    val markAsFixedWithSpecificVersion: (fixVersion: String) -> Unit,
    val changeReporter: (reporter: String) -> Unit,
    val addAttachment: (file: File, cleanupCallback: () -> Unit) -> Unit
)
