# This workflow will build a Java project with Gradle and deploy it

name: Build and push

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew clean installDist
    - name: Upload new libraries
      uses: urielsalis/rsync-deploy@v1.1
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_PORT: 22
        FOLDER: "build/install/arisa-kt/lib"
        ARGS: "-avh --delete"
        SERVER_IP: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        SERVER_DESTINATION: /home/ubuntu/arisa-kt
    - name: Upload new binaries
      uses: urielsalis/rsync-deploy@v1.1
      env:
        DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SERVER_PORT: 22
        FOLDER: "build/install/arisa-kt/bin"
        ARGS: "-avh --delete"
        SERVER_IP: ${{ secrets.REMOTE_HOST }}
        USERNAME: ${{ secrets.REMOTE_USER }}
        SERVER_DESTINATION: /home/ubuntu/arisa-kt
    - name: Run internal deploy script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: /home/ubuntu/arisa-kt/deploy.sh
