name: Build and deploy

permissions:
  id-token: write # Require write permission to Fetch an OIDC token.

on:
  push:
    branches: [ master ]
  # Allow manually triggering deployment
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: 17
        distribution: temurin

    - name: Set up Gradle
      uses: gradle/actions/setup-gradle@v5

    - name: Build with Gradle
      run: ./gradlew clean installDist build

    - name: Deploy
      uses: mojira/deploy@main
      with:
        vps_host: ${{ secrets.VPS_HOST }}
        vps_ssh_key: ${{ secrets.VPS_SSH_KEY }}
        vps_known_hosts: ${{ secrets.VPS_KNOWN_HOSTS }}
        project_folder: arisa
        script: |
          ./gradlew clean installDist build
          ./restart.sh
