name: Build and deploy

on:
  push:
    branches: [ master ]
  # Allow manually triggering deployment
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
      - name: Setup and build with Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean installDist
      - name: Upload new libraries
        uses: urielsalis/rsync-deploy@v1.4
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_PORT: 22
          FOLDER: "build/install/arisa-kt/lib"
          ARGS: "-avh --delete"
          SERVER_IP: ssh.urielsalis.com
          USERNAME: arisakt
          SERVER_DESTINATION: /home/arisakt/arisa-kt
      - name: Upload new binaries
        uses: urielsalis/rsync-deploy@v1.4
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_PORT: 22
          FOLDER: "build/install/arisa-kt/bin"
          ARGS: "-avh --delete"
          SERVER_IP: ssh.urielsalis.com
          USERNAME: arisakt
          SERVER_DESTINATION: /home/arisakt/arisa-kt
      - name: Upload new configuration
        uses: urielsalis/rsync-deploy@v1.4
        env:
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_PORT: 22
          FOLDER: "config"
          ARGS: "-avh --delete --exclude='local.yml'"
          SERVER_IP: ssh.urielsalis.com
          USERNAME: arisakt
          SERVER_DESTINATION: /home/arisakt/arisa-kt
      - name: Run internal deploy script
        uses: fifsky/ssh-action@master
        with:
          host: ssh.urielsalis.com
          user: arisakt
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command: |
            /usr/bin/screen -ls | /bin/egrep 'Detached|Attached' | /usr/bin/cut -d. -f1 | /usr/bin/awk '{print $1}' | /usr/bin/xargs /bin/kill
            sleep 1
            cd arisa-kt
            /usr/bin/screen -d -m bash -c '/home/arisakt/arisa-kt/bin/arisa-kt; exec sh'

          args: "-tt"
